name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: CC=gcc-12 CXX=g++-12 cmake -B ${{github.workspace}}/Build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/Build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/Build/Example
      run: ctest -C ${{env.BUILD_TYPE}}
